System check identified some issues:

WARNINGS:
[33;1mtitles.Title.genre: (fields.W340) null has no effect on ManyToManyField.[0m
[31;1mCommandError: Unable to serialize database: database connection isn't set to UTC
[0m[{"model": "contenttypes.contenttype", "pk": 1, "fields": {"app_label": "admin", "model": "logentry"}}, {"model": "contenttypes.contenttype", "pk": 2, "fields": {"app_label": "auth", "model": "permission"}}, {"model": "contenttypes.contenttype", "pk": 3, "fields": {"app_label": "auth", "model": "group"}}, {"model": "contenttypes.contenttype", "pk": 4, "fields": {"app_label": "contenttypes", "model": "contenttype"}}, {"model": "contenttypes.contenttype", "pk": 5, "fields": {"app_label": "sessions", "model": "session"}}, {"model": "contenttypes.contenttype", "pk": 6, "fields": {"app_label": "users", "model": "user"}}, {"model": "contenttypes.contenttype", "pk": 7, "fields": {"app_label": "titles", "model": "category"}}, {"model": "contenttypes.contenttype", "pk": 8, "fields": {"app_label": "titles", "model": "genre"}}, {"model": "contenttypes.contenttype", "pk": 9, "fields": {"app_label": "titles", "model": "title"}}, {"model": "contenttypes.contenttype", "pk": 10, "fields": {"app_label": "reviews", "model": "review"}}, {"model": "contenttypes.contenttype", "pk": 11, "fields": {"app_label": "reviews", "model": "comment"}}